### ISSUE TITLE
close() got an unexpected keyword argument 'downgrade'

### ISSUE THREAD

**Issue by RonilPatel7** [Arthur-Milchior/anki-window-open-on-sync#2]
```
Debug info:
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 7
Flags: frz=True ao=True sv=?
Add-ons, last update check: 2020-04-27 02:09:52

Caught exception:
Traceback (most recent call last):
File "C:\Users\RP\AppData\Roaming\Anki2\addons21\937448353\sync_thread.py", line 69, in run
self.col.close(save=False, downgrade=False)
TypeError: close() got an unexpected keyword argument 'downgrade'
``
```

**Comment by Arthur-Milchior** [comment]
It's strange. This add-on indicates it works with .24 and higher, you were not even supposed to have it work with .22.
Sorry, there is nothing I can do here, the only reason why this add-on came so late in Anki's history is because it uses extremely recent feature of anki'scode

**Comment by RonilPatel7** [comment]
This bug was seen originally on April 27, 2020; however it resolved after I downloaded the most recent version from ankiweb; no changes were necessary
